version: '3'
services:
  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: contalayback
      POSTGRES_DB: contalayback
    ports:
      - '8081:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
